### ISSUE TITLE
某些设备的加载动画出现异常

### ISSUE THREAD

**Issue by lmy1223** [BennyThink/GreenGrapes2#2]
某些设备的加载动画出现异常

**Comment by BennyThink** [comment]
在后续维护的主题[WordPressGit](https://github.com/BennyThink/WordPressGit)中，黑白纪念日重现了一个类似的bug：
Safari首页是黑白，文章彩色（并且下雪）；Chrome全部黑白，但是开启隐身模式则首页黑白、文章彩色（并且下雪）。
同样的问题在你的主题上没能出现。
需要进行进一步的调查。

**Comment by BennyThink** [comment]
好吧，我承认是我蠢，不知道怎么的加了个`$('#loading').remove(); `，自然就把加载动画移除了。
已经在[commit  3118112 ](https://github.com/BennyThink/GreenGrapes2/commit/31181126883bcf07e3880c8b3ca72b52a486f457)中修复，现在应该能够正常显示加载动画了。
