### ISSUE TITLE
 Database Query Error

### ISSUE THREAD

**Issue by nanxfu** [BennyThink/GreenGrapes2#5]
dalao ヽ (･ω･´ﾒ) 我用你的主题访问页面时会出现错误，错误码为 500，错误提示为 Database Query Error是怎么肥四_(:з」∠)_

**Comment by BennyThink** [comment]
@MushroomLittle 

没有日志这有点难判断。在typecho根目录下的index.php（或者config.inc.php也行）中的合适位置（比如说最后一行）加入如下一行
```php
define('__TYPECHO_DEBUG__',true);
```

然后刷新页面，把报错的详细日志贴上来

**Comment by nanxfu** [comment]
Warning: file_get_contents(http://192.168.1.111:8035/usr/themes/GreenGrapes2/js/fortunes.json):

failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found in /storage/emulated/legacy/blog/usr/themes/GreenGrapes/functions.php on line 434

**Comment by BennyThink** [comment]
@MushroomLittle
你贴的日志不对。这个只是警告，不会引起500的。

**Comment by nanxfu** [comment]
已经解决了(｀・ω・´)，原因是安装typecho的时候选的SQlite而不是MYSQL然后重装了一遍typecho数据库选的mysql就行了ヾ(=･ω･=)o

**Comment by BennyThink** [comment]
嗯 Sqlite的一些语法关键字和MySQL不太一样。
