### ISSUE TITLE
微信公众号地址错误，评论签到数据库错误

### ISSUE THREAD

**Issue by rumosky** [BennyThink/GreenGrapes2#6]
1，footer.php中的微信这一段代码：
`<?php if (!empty($this->options->weixinURL)) : ?><span class="fa-stack fa-lg">
<a class="fa fa-weixin fa-stack-1x" href="https://open.weixin.qq.com/qr/code/?username=<?php $this->options->weixinURL() ?>" target="view_window"></a>
</span><?php endif;?>`

微信公众号图片的链接写错了，应该是这样：https://open.weixin.qq.com/qr/code?username=微信号

不知道为什么，在主题后台填写了微信号，前台没有反应。

2，评论的签到功能打开后，提交评论会提示，database query error

补充一下，评论的粗体倾斜之类的功能，不知道是不是我不会写markdown语法，反正我测试时，你在评论里写什么，最后输出的还是什么，就是粗体那些代码没有渲染，直接以文本输出了。没有粗体的效果

**Comment by BennyThink** [comment]
1. 已修复，链接写错了，判断条件写错了
e9477f54306db725cafc1e355371dfd0246ad0ea 修复

2. 我测试没问题唉？开下typecho的debug看看有什么错误输出
3. 评论参见faq7
评论如何设置允许markdown语法？ 设置-评论-在评论中使用markdown语法，允许使用的内容和标签，如下内容即可： ```<blockquote><pre><code class=""><strong><em><h3><h4><h5><h6><a href title><table><thead><tr><th><tbody><td><img src="">```

**Comment by BennyThink** [comment]
database query error #5

**Comment by rumosky** [comment]
你好，那个签到的错误，我debug到了，错误如下
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x98' for column 'text' at row 1Typecho_Db_Query_Exception: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x98' for column 'text' at row 1 in /www/wwwroot/rumosky.net/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /www/wwwroot/rumosky.net/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('INSERT INTO typ...', Object(PDO), 2, 'INSERT')
#1 /www/wwwroot/rumosky.net/var/Widget/Abstract/Comments.php(189): Typecho_Db->query(Object(Typecho_Db_Query))
#2 /www/wwwroot/rumosky.net/var/Widget/Feedback.php(140): Widget_Abstract_Comments->insert(Array)
#3 /www/wwwroot/rumosky.net/var/Widget/Feedback.php(336): Widget_Feedback->comment()
#4 /www/wwwroot/rumosky.net/var/Typecho/Router.php(138): Widget_Feedback->action()
#5 /www/wwwroot/rumosky.net/index.php(23): Typecho_Router::dispatch()
#6 {main}
这个在Git上提交了。
最后，有个新的问题，这次的模板更新后，打赏插件貌似出了点小问题，点击支付宝或者微信按钮没有反应，二维码没有切换（上个版本模版是好的）
不知道是不是我这边的问题，附上域名：rumosky.net（测试站，很乱，希望别介意。）
谢谢作者热情的回复，很感动，因为以前很多作者的邮件都是石沉大海。再次感谢！

诚者，天之道也；诚之者，人之道也。


------------------------------------------------------------------
发件人：Benny <notifications@github.com>
发送时间：2018年11月8日(星期四) 10:55
收件人：BennyThink/GreenGrapes2 <GreenGrapes2@noreply.github.com>
抄　送：李斌斌 <lbb@rumosky.com>; Author <author@noreply.github.com>
主　题：Re: [BennyThink/GreenGrapes2] 微信公众号地址错误，评论签到数据库错误 (#6)

database query error #5

**Comment by BennyThink** [comment]
我晓得了，'\xF0\x9F\x98\x98'实际上是😘这个emoji，MySQL的字符集中的utf8mb4才是真正的utf-8，这样才支持emoji，typecho默认的连接字符集是utf8，所以需要做两件事情：
1. 修改config.php，把utf8都改成utf8mb4
2. 把对应的数据库的字符集改成utf8mb4

或者干脆评论里不用emoji。

**关于打赏**
我刚刚测试没问题唉？

有人用我就很开心了哈哈哈，所以~
