### ISSUE TITLE
网易云音乐插件无法使用

### ISSUE THREAD

**Issue by rumosky** [BennyThink/GreenGrapes2#7]
格式{{id}}
我在两个括号里面填上了id，但是，有的歌曲可以显示，有的歌曲直接都没有显示歌曲名。
显示歌曲名的也无法播放，点击播放没有反应。

**Comment by BennyThink** [comment]
原因可能是因为网易云音乐的版权保护，所以导致某些歌曲能够添加并显示，但是实际上并不可以播放外链。
![image](https://user-images.githubusercontent.com/14024832/48173056-34043000-e33d-11e8-95e3-2dbfada03329.png)
